// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using class09.EF.Database;

#nullable disable

namespace class09.EF.Migrations
{
    [DbContext(typeof(AcademyDbContext))]
    partial class AcademyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("class09.EF.Models.Entites.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfClasses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C# Basic",
                            NumberOfClasses = 10
                        },
                        new
                        {
                            Id = 2,
                            Name = "C# Advanced",
                            NumberOfClasses = 15
                        });
                });

            modelBuilder.Entity("class09.EF.Models.Entites.Student", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("ActiveCourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveCourseId = 1,
                            DateOfBirth = new DateTime(2002, 7, 3, 15, 43, 40, 472, DateTimeKind.Local).AddTicks(4703),
                            FirstName = "Bob",
                            LastName = "Bobsky"
                        },
                        new
                        {
                            Id = 2,
                            ActiveCourseId = 2,
                            DateOfBirth = new DateTime(1997, 7, 3, 15, 43, 40, 472, DateTimeKind.Local).AddTicks(4756),
                            FirstName = "Jill",
                            LastName = "Wayne"
                        },
                        new
                        {
                            Id = 3,
                            ActiveCourseId = 1,
                            DateOfBirth = new DateTime(2007, 7, 3, 15, 43, 40, 472, DateTimeKind.Local).AddTicks(4759),
                            FirstName = "John",
                            LastName = "Doe"
                        });
                });

            modelBuilder.Entity("class09.EF.Models.Entites.Student", b =>
                {
                    b.HasOne("class09.EF.Models.Entites.Course", "ActiveCourse")
                        .WithMany("Students")
                        .HasForeignKey("ActiveCourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActiveCourse");
                });

            modelBuilder.Entity("class09.EF.Models.Entites.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
