// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalMovie.Database;

#nullable disable

namespace RentalMovie.Database.Migrations
{
    [DbContext(typeof(RentalMovieDbContext))]
    partial class RentalMovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalMovie.Domain.Cast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Part")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            Name = "Ken Watanabe",
                            Part = 0
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            Name = "Park Chan-wook",
                            Part = 1
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 2,
                            Name = "Lee Byung-hun",
                            Part = 0
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 3,
                            Name = "Michael B. Jordan",
                            Part = 2
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 4,
                            Name = "Marion Cotillard",
                            Part = 0
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 7,
                            Name = "Tom Hardy",
                            Part = 0
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 8,
                            Name = "Jessica Chastain",
                            Part = 1
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 9,
                            Name = "Donnie Yen",
                            Part = 0
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 3,
                            Name = "Zoe Saldana",
                            Part = 2
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 6,
                            Name = "Owen Wilson",
                            Part = 0
                        });
                });

            modelBuilder.Entity("RentalMovie.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgeRestriction")
                        .HasColumnType("int");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Length")
                        .HasColumnType("time");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 13,
                            Genre = 3,
                            ImagePath = "/images/movies/sci-fi.jpg",
                            IsAvailable = true,
                            Language = 6,
                            Length = new TimeSpan(0, 2, 23, 0, 0),
                            Quantity = 5,
                            ReleaseDate = new DateTime(2012, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neon Shadows"
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 18,
                            Genre = 6,
                            ImagePath = "/images/movies/thriller.jpg",
                            IsAvailable = true,
                            Language = 2,
                            Length = new TimeSpan(0, 2, 12, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Silent Forest"
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 13,
                            Genre = 3,
                            ImagePath = "/images/movies/sci-fi.jpg",
                            IsAvailable = false,
                            Language = 0,
                            Length = new TimeSpan(0, 2, 23, 0, 0),
                            Quantity = 0,
                            ReleaseDate = new DateTime(2012, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Quantum Paradox"
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 10,
                            Genre = 7,
                            ImagePath = "/images/movies/adventure.jpg",
                            IsAvailable = true,
                            Language = 3,
                            Length = new TimeSpan(0, 2, 49, 0, 0),
                            Quantity = 4,
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Celestial Voyage"
                        },
                        new
                        {
                            Id = 5,
                            AgeRestriction = 18,
                            Genre = 4,
                            ImagePath = "/images/movies/horror.jpg",
                            IsAvailable = true,
                            Language = 1,
                            Length = new TimeSpan(0, 2, 26, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(1980, 5, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Whispers in the Dark"
                        },
                        new
                        {
                            Id = 6,
                            AgeRestriction = 12,
                            Genre = 5,
                            ImagePath = "/images/movies/romance.jpg",
                            IsAvailable = true,
                            Language = 3,
                            Length = new TimeSpan(0, 2, 2, 0, 0),
                            Quantity = 3,
                            ReleaseDate = new DateTime(2001, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight in Paris"
                        },
                        new
                        {
                            Id = 7,
                            AgeRestriction = 13,
                            Genre = 10,
                            ImagePath = "/images/movies/mystery.jpg",
                            IsAvailable = false,
                            Language = 4,
                            Length = new TimeSpan(0, 1, 56, 0, 0),
                            Quantity = 0,
                            ReleaseDate = new DateTime(1997, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Forgotten Letter"
                        },
                        new
                        {
                            Id = 8,
                            AgeRestriction = 17,
                            Genre = 4,
                            ImagePath = "/images/movies/horror.jpg",
                            IsAvailable = true,
                            Language = 0,
                            Length = new TimeSpan(0, 1, 44, 0, 0),
                            Quantity = 6,
                            ReleaseDate = new DateTime(2017, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Crimson Peak"
                        },
                        new
                        {
                            Id = 9,
                            AgeRestriction = 13,
                            Genre = 0,
                            ImagePath = "/images/movies/action.jpg",
                            IsAvailable = true,
                            Language = 8,
                            Length = new TimeSpan(0, 2, 28, 0, 0),
                            Quantity = 7,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Rogue Agent"
                        },
                        new
                        {
                            Id = 10,
                            AgeRestriction = 15,
                            Genre = 9,
                            ImagePath = "/images/movies/fantasy.jpg",
                            IsAvailable = true,
                            Language = 1,
                            Length = new TimeSpan(0, 1, 58, 0, 0),
                            Quantity = 2,
                            ReleaseDate = new DateTime(2006, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Alchemist's Daughter"
                        });
                });

            modelBuilder.Entity("RentalMovie.Domain.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieId = 1,
                            RentedOn = new DateTime(2025, 7, 13, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7905),
                            ReturnedOn = new DateTime(2025, 7, 18, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7909),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            MovieId = 2,
                            RentedOn = new DateTime(2025, 7, 15, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7916),
                            ReturnedOn = new DateTime(2025, 7, 21, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7917),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            MovieId = 3,
                            RentedOn = new DateTime(2025, 7, 16, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7919),
                            ReturnedOn = new DateTime(2025, 7, 22, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7920),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            MovieId = 4,
                            RentedOn = new DateTime(2025, 7, 18, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7922),
                            ReturnedOn = new DateTime(2025, 7, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7923),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            MovieId = 5,
                            RentedOn = new DateTime(2025, 7, 11, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7925),
                            ReturnedOn = new DateTime(2025, 7, 16, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7926),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            MovieId = 6,
                            RentedOn = new DateTime(2025, 7, 20, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7928),
                            ReturnedOn = new DateTime(2025, 7, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7929),
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            MovieId = 7,
                            RentedOn = new DateTime(2025, 7, 19, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7931),
                            ReturnedOn = new DateTime(2025, 7, 22, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7932),
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            MovieId = 8,
                            RentedOn = new DateTime(2025, 7, 21, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7933),
                            ReturnedOn = new DateTime(2025, 7, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7935),
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            MovieId = 9,
                            RentedOn = new DateTime(2025, 7, 17, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7936),
                            ReturnedOn = new DateTime(2025, 7, 21, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7938),
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            MovieId = 10,
                            RentedOn = new DateTime(2025, 7, 22, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7939),
                            ReturnedOn = new DateTime(2025, 7, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7940),
                            UserId = 10
                        });
                });

            modelBuilder.Entity("RentalMovie.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSubscriptionExpired")
                        .HasColumnType("bit");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            CardNumber = "1111-2222",
                            CreatedOn = new DateTime(2025, 1, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7703),
                            FullName = "Emma Watson",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 0
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            CardNumber = "2222-3333",
                            CreatedOn = new DateTime(2024, 11, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7752),
                            FullName = "James Wilson",
                            IsSubscriptionExpired = true,
                            SubscriptionType = 1
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            CardNumber = "3333-4444",
                            CreatedOn = new DateTime(2024, 7, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7758),
                            FullName = "Olivia Martinez",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 0
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            CardNumber = "4444-5555",
                            CreatedOn = new DateTime(2025, 4, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7760),
                            FullName = "Liam Anderson",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 1
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            CardNumber = "5555-6666",
                            CreatedOn = new DateTime(2023, 7, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7763),
                            FullName = "Sophia Garcia",
                            IsSubscriptionExpired = true,
                            SubscriptionType = 0
                        },
                        new
                        {
                            Id = 6,
                            Age = 40,
                            CardNumber = "6666-7777",
                            CreatedOn = new DateTime(2024, 9, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7766),
                            FullName = "Noah Taylor",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 29,
                            CardNumber = "7777-8888",
                            CreatedOn = new DateTime(2025, 2, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7768),
                            FullName = "Ava Lopez",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 0
                        },
                        new
                        {
                            Id = 8,
                            Age = 33,
                            CardNumber = "8888-9999",
                            CreatedOn = new DateTime(2025, 6, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7770),
                            FullName = "William Hernandez",
                            IsSubscriptionExpired = true,
                            SubscriptionType = 1
                        },
                        new
                        {
                            Id = 9,
                            Age = 21,
                            CardNumber = "9999-0000",
                            CreatedOn = new DateTime(2024, 12, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7772),
                            FullName = "Mia Gonzalez",
                            IsSubscriptionExpired = false,
                            SubscriptionType = 0
                        },
                        new
                        {
                            Id = 10,
                            Age = 27,
                            CardNumber = "0000-1111",
                            CreatedOn = new DateTime(2025, 3, 23, 8, 5, 51, 140, DateTimeKind.Local).AddTicks(7775),
                            FullName = "Benjamin Clark",
                            IsSubscriptionExpired = true,
                            SubscriptionType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
